'\" e
.\" ** The above line should force eqn to be a preprocessor **
.TH FILEPRUNE 1 "12 February 2022"
.\"
.\"  Copyright 2002-2022 Diomidis Spinellis
.\"
.\"  Licensed under the Apache License, Version 2.0 (the "License");
.\"  you may not use this file except in compliance with the License.
.\"  You may obtain a copy of the License at
.\"
.\"      http://www.apache.org/licenses/LICENSE-2.0
.\"
.\"  Unless required by applicable law or agreed to in writing, software
.\"  distributed under the License is distributed on an "AS IS" BASIS,
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\"  See the License for the specific language governing permissions and
.\"  limitations under the License.
.\"
.SH NAME
fileprune \- prune a file set according to a given age distribution
.SH SYNOPSIS
\fBfileprune\fP
[\fB\-n\fP|\fB\-N\fP|\fB\-p\fP]
[\fB\-c\fP \fIcount\fP|\fB\-s\fP \fIsize\fP|\fB\-S\fP \fIsize\fP|\fB\-a\fP \fIage\fP]
[\fB\-e\fP \fIbase\fP|\fB\-g\fP \fIstandard deviation\fP|\fB\-f\fP]
[\fB\-t\fP \fBa\fP|\fBm\fP|\fBc\fP|\fIformat\fP]
[\fB\-FKYv\fP]
\fIfile\fR ...
.br
\fBfileprune\fP
\fB-d\fP
\fB\-n\fP|\fB\-N
[\fB\-c\fP \fIcount\fP|\fB\-a\fP \fIage\fP]
[\fB\-e\fP \fIbase\fP|\fB\-g\fP \fIstandard deviation\fP|\fB\-f\fP]
[\fB\-FKYv\fP]
\fIdate\fR ...
.SH DESCRIPTION
\fIFileprune\fP
will delete files or directories from the specified set
targeting a given distribution
of the files within time as well as size, number, and age constraints.
Its main purpose is to keep a set of daily-created backup files
in manageable size,
while still providing reasonable access to older versions.
Specifying a size, file number, or age constraint will
simply remove files starting from the oldest, until the
constraint is met.
The distribution specification (exponential, Gaussian (normal), or Fibonacci)
provides finer control of the files to delete,
allowing the retention of recent copies and the increasingly
aggressive pruning of the older files.
The retention schedule specifies the age intervals for which files
will be retained.
As an example, an exponential retention schedule for 10 files
with a base of 2 will be
.IP
1 2 4 8 16 32 64 128 256 512 1024
.PP
The above schedule specifies that for the interval of 65 to 128
days there should be (at least) one retained file (unless constraints
and options override this setting).
Retention schedules are always calculated and evaluated in integer days.
By default \fIfileprune\fP will keep the oldest file within each day interval
allowing files to migrate from one interval to the next as time goes by.
It may also keep additional files, if the complete file set satisfies
the specified constraint.
The algorithm used for pruning does not assume that the files are
uniformly distributed;
\fIfileprune\fP will successfully prune file collections stored at
irregular intervals.

.SH OPTIONS
.IP "\fB\-n\fP"
Do not delete files; only print file names that would be deleted.
.IP "\fB\-N\fP"
Do not delete files; only print file names that would be retained.
.IP "\fB\-p\fP"
Do not process files.
Print the specified schedule for \fIcount\fP elements.
.IP "\fB\-c\fP \fIcount\fP"
Keep \fIcount\fP files.
A count of zero will prune all specified files.
.IP "\fB\-s\fP \fIsize\fP"
Keep files totaling at most \fIsize\fP bytes.
The \fIsize\fP argument can be followed by a
\fBk\fP, \fBm\fP, \fBg\fP, or \fBt\fP uppercase or lowercase suffix
to express quantities from kilobytes to terabytes.
This option cannot be used when the specified arguments refer to directories.
.IP "\fB\-S\fP \fIsize\fP"
Ensure that at least \fIsize\fP bytes will be available on disk
after the files get deleted.
The \fIsize\fP argument can be followed by a unit suffix
as in the case in the \fB-s\fP option.
.IP "\fB\-a\fP \fIage\fP"
Keep files up to the specified \fIage\fP.
The \fIage\fP argument can be followed by a
\fBw\fP, \fBm\fP, or \fBy\fP suffix to specify
weeks, months, or years.
.IP "\fB\-e\fP \fIbase\fP"
Use an exponential distribution of the specified \fIbase\fP \fIb\fP for pruning.
Each successive interval \fIn\fP will end at
.EQ
b sup n .
.EN
As an example, a base of 2 will retain 10 files in a period of 1024 days.
To determine the exponent for keeping \fIn\fP files in a period
of \fId\fP days use the formula
.EQ
exponent = e sup {ln d over n} .
.EN
.\" \fIexponent\fP = exp(ln(\fId\fP)/\fIn\fP).
.IP "\fB\-g\fP \fIsd\fP"
Use a Gaussian (normal) distribution with the given \fIstandard deviation\fP
for the pruning schedule.
The height of the curve with a standard deviation of \(*s is given by the
formula
.\" f(\fIx\fP) = 1 / (\(s \(sr(2 \(*p)) exp(-\fIx\fP\s-2\u2\d\s0 / 2 / \(s\s-2\u2\d\s0);
.EQ
f(x) = 1 over { sqrt{2 pi } sigma } e sup {-x sup 2 over {2 sigma  sup 2}} .
.EN
All intervals from \fIa\fP to \fIb\fP are calculated to have the same
.EQ
int from a to b f(x) dx .
.EN
The standard deviation is specified in day units;
as a rule of a thumb the oldest file retained will have an age of twice the
standard deviation.
.IP "\fB\-f\fP"
Use a Fibonacci distribution for the pruning schedule.
The Fibonacci sequence starts with 0, 1, and each subsequent term is the sum
of the two previous ones.
.IP "\fB\-t\fP \fBa\fP|\fB\m\fP|\fBc\fP|\fIformat\fP"
For determining a file's age use its access, modification, or
creation time.
By default the modification time is used.
If a data format string is provided rather than a single character,
then this is passed to \fIstrptime(3)\fP,
in order to obtain the file's age from its file name.
.IP "\fB\-F\fP"
Force file pruning even if the size or count constraint has
not been exceeded.
.IP "\fB\-K\fP"
Keep files scheduled in each pruning interval,
even if the size or count constraint has been exceeded.
.IP "\fB\-Y\fP"
Never delete the youngest file, even if other options lead to that.
.IP "\fB\-v\fP"
Operate in verbose mode, printing the name of each deleted file.
Specifying this option a second time will print additional debugging
information.
.IP "\fB\-d\fP"
Use a list of ISO dates rather than files as an argument of the pruning schedule.
Each date argument must be of the form \fIYYYY-MM-DD \fP[\fIhh\fP[:\fImm\fP[:\fIss\fP]]].
This option must be used with one of the \fB\-N\fP or \fB\-n\fP options,
and cannot be combined with the \fB\-t\fP or \fB\-s\fP options.

.SH EXAMPLE
.PP
.ft C
ssh remotehost tar cf - /datafiles >backup/`date +'%Y%m%d'`
.br
fileprune -e 2 backup/*
.ft P
.br
Backup \fIremotehost\fP, storing the result in a file
named with today's timestamp (e.g. 20021219).
Prune the files in the backup directory
so that each retained file's age will be double that of its
immediately younger neighbor.
.PP
.ft C
fileprune -N -d -e 1.2 -c 40 *
.ft P
.br
Keep at most 40 files.
This particular distribution will result in daily copies for
the first fortnight, at least weekly for the next month, and
almost monthly for the first year.
.PP
.ft C
fileprune -g 365 -c 30 *
.ft P
.br
Keep at most 30 files with their ages following a
Gaussian (normal) distribution with a standard deviation of one year.
.PP
.ft C
fileprune -e 2 -s 5G *
.ft P
.br
Prune the specified files following an
exponential schedule so that no more than
5GB are occupied.
More than one file may be left in an interval,
if the size constraint is met.
Alternatively, some old intervals may be emptied in order
to satisfy the size constraint.
.PP
.ft C
fileprune -F -e 2 -s 5G *
.ft P
.br
As above, but leave no more than one file in each scheduled interval.
.PP
.ft C
fileprune -K -e 2 -s 5G *
.ft P
.br
As in the first example of the %g-constrained series,
but leave exactly one file in each interval,
even if this will violate the size constraint.
.PP
.ft C
fileprune -a 1m -f
.ft P
.br
Delete all files older than one month use;
use a Fibonacci distribution for pruning the remaining ones.
.PP
.ft C
.nf
SNAPSHOTS=/tmp/snapshots.$$
ec2-describe-snapshots --filter status=completed |
awk '$1 == "SNAPSHOT" {print $2, substr($5, 1, 10)}' |
sort -k2 >$SNAPSHOTS
fileprune -n -d -e 1.2 -c 40 `awk '{print $2}' $SNAPSHOTS` |
sort |
join -1 1 -2 2 -o 2.1 - $SNAPSHOTS |
xargs -n 1 ec2-delete-snapshot
rm -f $SNAPSHOTS
.fi
.ft P
.br
Prune AWS-hosted daily snapshots to leave 40.
.SH "SEE ALSO"
newsyslog(8)
.SH AUTHOR
(C) Copyright 2002-2016 Diomidis Spinellis.
.SH BUGS
The Gaussian (normal) distribution is calculated by trying successive
increments of the normal function's distribution function.
If the file number or count is large compared to the
specified standard deviation, the calculation may take
an exceedingly long time.
To get results in a reasonable time,
day increments are bounded at 10 times the increment of the previous interval
and a total age of 100 years.
It is advisable to first calculate and
print the pruning schedule with a command like
.br
.ft C
fileprune -g 100 -p -c 20
.ft P
.br
to ensure that the schedule can be calculated.
